build: disable `win_arm64` for now
build fails on default 'azure' provider with:

> error: linking with `link.exe` failed: exit code: 1120
> fatal error LNK1120: 13 unresolved externals

because of `libonig_sys` (`warning LNK4272: library machine type 'ARM64'
conflicts with target machine type 'x64'`)